<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Svg\\' => array($vendorDir . '/phenx/php-svg-lib/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'PhpConsole' => array($vendorDir . '/php-console/php-console/src'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'DocBlockReader' => array($vendorDir . '/jan-swiecki/simple-annotations/src'),
);
